In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
pwd = os.getcwd()
game_schedule = pd.read_csv(pwd + "/../datasets/full_schedule.csv")
game_schedule

Date        Visitor/Neutral  Away_PTS  \
0     Tue, Dec 22, 2020  Golden State Warriors      99.0   
1     Tue, Dec 22, 2020   Los Angeles Clippers     116.0   
2     Wed, Dec 23, 2020      Charlotte Hornets     114.0   
3     Wed, Dec 23, 2020        New York Knicks     107.0   
4     Wed, Dec 23, 2020             Miami Heat     107.0   
...                 ...                    ...       ...   
1006   Sat, May 8, 2021      Memphis Grizzlies     109.0   
1007   Sat, May 8, 2021          Brooklyn Nets     125.0   
1008   Sat, May 8, 2021  Oklahoma City Thunder      97.0   
1009   Sat, May 8, 2021      San Antonio Spurs     102.0   
1010   Sat, May 8, 2021        Houston Rockets     116.0   

                Home/Neutral  Home_PTS Home/Away Winner  \
0              Brooklyn Nets     125.0             Home   
1         Los Angeles Lakers     109.0          Visitor   
2        Cleveland Cavaliers     121.0             Home   
3             Indiana Pacers     121.0             Home   
4              Orlando Magic     113.0             Home   
...                      ...       ...              ...   
1006         Toronto Raptors      99.0          Visitor   
1007          Denver Nuggets     119.0          Visitor   
1008   Golden State Warriors     136.0             Home   
1009  Portland Trail Blazers     124.0             Home   
1010               Utah Jazz     124.0             Home   

                Winning Team  Margin of Victory  
0              Brooklyn Nets               26.0  
1       Los Angeles Clippers                7.0  
2        Cleveland Cavaliers                7.0  
3             Indiana Pacers               14.0  
4              Orlando Magic                6.0  
...                      ...                ...  
1006       Memphis Grizzlies               10.0  
1007           Brooklyn Nets                6.0  
1008   Golden State Warriors               39.0  
1009  Portland Trail Blazers               22.0  
1010               Utah Jazz                8.0  

[1011 rows x 8 columns]

In [3]:
nine_feature_team_stats = pd.read_csv(pwd + "/../datasets/9_relevant_team_stats.csv")
nine_feature_team_stats

Team    FG%    3P%  BLK_opponent    MOV   SRS   ORtg  \
0            Brooklyn Nets  0.493  0.388           4.6   4.42  4.05  118.3   
1          Milwaukee Bucks  0.486  0.392           4.9   6.32  6.18  116.7   
2                Utah Jazz  0.467  0.391           3.9   9.06  9.01  117.5   
3     Los Angeles Clippers  0.482  0.416           4.1   6.03  6.04  117.9   
4           Denver Nuggets  0.488  0.380           4.3   5.36  5.09  117.5   
5     New Orleans Pelicans  0.482  0.351           5.7   0.42  0.33  114.5   
6       Washington Wizards  0.473  0.350           4.8  -2.53 -2.48  110.4   
7            Atlanta Hawks  0.462  0.370           5.1   1.17  1.27  114.7   
8   Portland Trail Blazers  0.448  0.380           4.8   0.51  0.41  116.8   
9   Minnesota Timberwolves  0.445  0.350           5.7  -6.55 -6.16  108.7   
10   Golden State Warriors  0.465  0.374           4.5  -0.28 -0.16  110.1   
11          Indiana Pacers  0.471  0.361           5.3   0.02 -0.04  112.1   
12            Phoenix Suns  0.489  0.373           3.6   6.16  6.15  116.4   
13          Boston Celtics  0.466  0.372           4.6   1.73  1.93  114.0   
14        Sacramento Kings  0.482  0.365           4.6  -4.73 -4.19  114.2   
15      Philadelphia 76ers  0.476  0.371           4.6   5.35  5.51  112.8   
16         Toronto Raptors  0.450  0.371           5.7   0.36  0.07  112.5   
17       Memphis Grizzlies  0.466  0.356           5.3   0.94  1.18  111.7   
18           Chicago Bulls  0.478  0.365           5.0  -1.61 -1.85  110.9   
19        Dallas Mavericks  0.470  0.362           3.8   2.10  2.38  115.0   
20       Charlotte Hornets  0.458  0.377           4.7  -1.22 -1.18  111.2   
21      Los Angeles Lakers  0.474  0.352           4.5   3.13  2.87  109.9   
22         Houston Rockets  0.441  0.335           5.3  -7.39 -7.48  106.3   
23       San Antonio Spurs  0.462  0.356           5.1  -0.53 -1.11  111.3   
24         Detroit Pistons  0.450  0.355           6.0  -3.98 -3.78  108.4   
25              Miami Heat  0.463  0.350           4.1  -0.44 -0.58  109.9   
26         New York Knicks  0.457  0.387           5.6   2.30  1.93  110.8   
27   Oklahoma City Thunder  0.442  0.342           5.2 -10.06 -9.66  103.5   
28           Orlando Magic  0.430  0.346           5.3  -8.25 -8.08  105.3   
29     Cleveland Cavaliers  0.454  0.338           5.5  -7.48 -7.43  106.0   

    NRtg    TS%   eFG%  
0    4.4  0.608  0.573  
1    6.1  0.593  0.565  
2    9.2  0.596  0.563  
3    6.2  0.599  0.564  
4    5.4  0.591  0.561  
5    0.4  0.576  0.543  
6   -2.4  0.568  0.530  
7    1.1  0.576  0.533  
8    0.5  0.572  0.534  
9   -6.4  0.552  0.517  
10  -0.3  0.578  0.546  
11   0.0  0.573  0.540  
12   6.3  0.594  0.562  
13   1.8  0.574  0.542  
14  -4.8  0.581  0.551  
15   5.3  0.578  0.540  
16   0.4  0.572  0.533  
17   1.0  0.559  0.526  
18  -1.6  0.576  0.548  
19   2.2  0.581  0.549  
20  -1.3  0.569  0.538  
21   3.1  0.570  0.538  
22  -7.3  0.549  0.517  
23  -0.5  0.556  0.520  
24  -4.0  0.556  0.518  
25  -0.5  0.575  0.538  
26   2.4  0.558  0.523  
27  -9.9  0.542  0.511  
28  -8.4  0.528  0.492  
29  -7.6  0.545  0.512

In [89]:
processing_data = game_schedule

In [90]:
away_fg = []
away_3p = []
away_blk_opponent = []
away_mov = []
away_srs = []
away_ortg = []
away_nrtg = []
away_ts = []
away_efg = []

for index, row in processing_data.iterrows():
    away_team = row["Visitor/Neutral"]
    for index1, row1 in nine_feature_team_stats.iterrows():
        if row1["Team"] == away_team:
            away_fg.append(row1["FG%"])
            away_3p.append(row1["3P%"])
            away_blk_opponent.append(row1["BLK_opponent"])
            away_mov.append(row1["MOV"])
            away_srs.append(row1["SRS"])
            away_ortg.append(row1["ORtg"])
            away_nrtg.append(row1["NRtg"])
            away_ts.append(row1["TS%"])
            away_efg.append(row1["eFG%"])
len(away_fg)

1011

In [91]:
home_fg = []
home_3p = []
home_blk_opponent = []
home_mov = []
home_srs = []
home_ortg = []
home_nrtg = []
home_ts = []
home_efg = []

for index, row in processing_data.iterrows():
    home_team = row["Home/Neutral"]
    for index1, row1 in nine_feature_team_stats.iterrows():
        if row1["Team"] == home_team:
            home_fg.append(row1["FG%"])
            home_3p.append(row1["3P%"])
            home_blk_opponent.append(row1["BLK_opponent"])
            home_mov.append(row1["MOV"])
            home_srs.append(row1["SRS"])
            home_ortg.append(row1["ORtg"])
            home_nrtg.append(row1["NRtg"])
            home_ts.append(row1["TS%"])
            home_efg.append(row1["eFG%"])
len(home_fg)

1011

In [92]:
 processing_data.drop(columns=["Date", "Visitor/Neutral", "Away_PTS", "Home/Neutral", "Home_PTS", "Winning Team", "Margin of Victory"], inplace=True)
 processing_data

Home/Away Winner
0                Home
1             Visitor
2                Home
3                Home
4                Home
...               ...
1006          Visitor
1007          Visitor
1008             Home
1009             Home
1010             Home

[1011 rows x 1 columns]

In [94]:
processing_data["away_FG%"] = away_fg
processing_data["away_3P%"] = away_3p
processing_data["away_opponent_BLK"] = away_blk_opponent
processing_data["away_MOV"] = away_mov
processing_data["away_SRS"] = away_srs
processing_data["away_ORtg"] = away_ortg
processing_data["away_NRtg"] = away_nrtg
processing_data["away_TS%"] = away_ts
processing_data["away_eFG%"] = away_efg

processing_data["home_FG%"] = home_fg
processing_data["home_3P%"] = home_3p
processing_data["home_opponent_BLK"] = home_blk_opponent
processing_data["home_MOV"] = home_mov
processing_data["home_SRS"] = home_srs
processing_data["home_ORtg"] = home_ortg
processing_data["home_NRtg"] = home_nrtg
processing_data["home_TS%"] = home_ts
processing_data["home_eFG%"] = home_efg

processing_data

Home/Away Winner  away_FG%  away_3P%  away_opponent_BLK  away_MOV  \
0                Home     0.465     0.374                4.5     -0.28   
1             Visitor     0.482     0.416                4.1      6.03   
2                Home     0.458     0.377                4.7     -1.22   
3                Home     0.457     0.387                5.6      2.30   
4                Home     0.463     0.350                4.1     -0.44   
...               ...       ...       ...                ...       ...   
1006          Visitor     0.466     0.356                5.3      0.94   
1007          Visitor     0.493     0.388                4.6      4.42   
1008             Home     0.442     0.342                5.2    -10.06   
1009             Home     0.462     0.356                5.1     -0.53   
1010             Home     0.441     0.335                5.3     -7.39   

      away_SRS  away_ORtg  away_NRtg  away_TS%  away_eFG%  home_FG%  home_3P%  \
0        -0.16      110.1       -0.3     0.578      0.546     0.493     0.388   
1         6.04      117.9        6.2     0.599      0.564     0.474     0.352   
2        -1.18      111.2       -1.3     0.569      0.538     0.454     0.338   
3         1.93      110.8        2.4     0.558      0.523     0.471     0.361   
4        -0.58      109.9       -0.5     0.575      0.538     0.430     0.346   
...        ...        ...        ...       ...        ...       ...       ...   
1006      1.18      111.7        1.0     0.559      0.526     0.450     0.371   
1007      4.05      118.3        4.4     0.608      0.573     0.488     0.380   
1008     -9.66      103.5       -9.9     0.542      0.511     0.465     0.374   
1009     -1.11      111.3       -0.5     0.556      0.520     0.448     0.380   
1010     -7.48      106.3       -7.3     0.549      0.517     0.467     0.391   

      home_opponent_BLK  home_MOV  home_SRS  home_ORtg  home_NRtg  home_TS%  \
0                   4.6      4.42      4.05      118.3        4.4     0.608   
1                   4.5      3.13      2.87      109.9        3.1     0.570   
2                   5.5     -7.48     -7.43      106.0       -7.6     0.545   
3                   5.3      0.02     -0.04      112.1        0.0     0.573   
4                   5.3     -8.25     -8.08      105.3       -8.4     0.528   
...                 ...       ...       ...        ...        ...       ...   
1006                5.7      0.36      0.07      112.5        0.4     0.572   
1007                4.3      5.36      5.09      117.5        5.4     0.591   
1008                4.5     -0.28     -0.16      110.1       -0.3     0.578   
1009                4.8      0.51      0.41      116.8        0.5     0.572   
1010                3.9      9.06      9.01      117.5        9.2     0.596   

      home_eFG%  
0         0.573  
1         0.538  
2         0.512  
3         0.540  
4         0.492  
...         ...  
1006      0.533  
1007      0.561  
1008      0.546  
1009      0.534  
1010      0.563  

[1011 rows x 19 columns]

In [95]:
y = processing_data["Home/Away Winner"]
y

0          Home
1       Visitor
2          Home
3          Home
4          Home
         ...   
1006    Visitor
1007    Visitor
1008       Home
1009       Home
1010       Home
Name: Home/Away Winner, Length: 1011, dtype: object

In [96]:
X = processing_data.iloc[:, 1:]
X

away_FG%  away_3P%  away_opponent_BLK  away_MOV  away_SRS  away_ORtg  \
0        0.465     0.374                4.5     -0.28     -0.16      110.1   
1        0.482     0.416                4.1      6.03      6.04      117.9   
2        0.458     0.377                4.7     -1.22     -1.18      111.2   
3        0.457     0.387                5.6      2.30      1.93      110.8   
4        0.463     0.350                4.1     -0.44     -0.58      109.9   
...        ...       ...                ...       ...       ...        ...   
1006     0.466     0.356                5.3      0.94      1.18      111.7   
1007     0.493     0.388                4.6      4.42      4.05      118.3   
1008     0.442     0.342                5.2    -10.06     -9.66      103.5   
1009     0.462     0.356                5.1     -0.53     -1.11      111.3   
1010     0.441     0.335                5.3     -7.39     -7.48      106.3   

      away_NRtg  away_TS%  away_eFG%  home_FG%  home_3P%  home_opponent_BLK  \
0          -0.3     0.578      0.546     0.493     0.388                4.6   
1           6.2     0.599      0.564     0.474     0.352                4.5   
2          -1.3     0.569      0.538     0.454     0.338                5.5   
3           2.4     0.558      0.523     0.471     0.361                5.3   
4          -0.5     0.575      0.538     0.430     0.346                5.3   
...         ...       ...        ...       ...       ...                ...   
1006        1.0     0.559      0.526     0.450     0.371                5.7   
1007        4.4     0.608      0.573     0.488     0.380                4.3   
1008       -9.9     0.542      0.511     0.465     0.374                4.5   
1009       -0.5     0.556      0.520     0.448     0.380                4.8   
1010       -7.3     0.549      0.517     0.467     0.391                3.9   

      home_MOV  home_SRS  home_ORtg  home_NRtg  home_TS%  home_eFG%  
0         4.42      4.05      118.3        4.4     0.608      0.573  
1         3.13      2.87      109.9        3.1     0.570      0.538  
2        -7.48     -7.43      106.0       -7.6     0.545      0.512  
3         0.02     -0.04      112.1        0.0     0.573      0.540  
4        -8.25     -8.08      105.3       -8.4     0.528      0.492  
...        ...       ...        ...        ...       ...        ...  
1006      0.36      0.07      112.5        0.4     0.572      0.533  
1007      5.36      5.09      117.5        5.4     0.591      0.561  
1008     -0.28     -0.16      110.1       -0.3     0.578      0.546  
1009      0.51      0.41      116.8        0.5     0.572      0.534  
1010      9.06      9.01      117.5        9.2     0.596      0.563  

[1011 rows x 18 columns]

In [97]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

away_FG%  away_3P%  away_opponent_BLK  away_MOV  away_SRS  away_ORtg  \
694     0.462     0.370                5.1      1.17      1.27      114.7   
265     0.471     0.361                5.3      0.02     -0.04      112.1   
318     0.488     0.380                4.3      5.36      5.09      117.5   
649     0.462     0.370                5.1      1.17      1.27      114.7   
785     0.466     0.372                4.6      1.73      1.93      114.0   
..        ...       ...                ...       ...       ...        ...   
106     0.454     0.338                5.5     -7.48     -7.43      106.0   
270     0.476     0.371                4.6      5.35      5.51      112.8   
860     0.493     0.388                4.6      4.42      4.05      118.3   
435     0.463     0.350                4.1     -0.44     -0.58      109.9   
102     0.445     0.350                5.7     -6.55     -6.16      108.7   

     away_NRtg  away_TS%  away_eFG%  home_FG%  home_3P%  home_opponent_BLK  \
694        1.1     0.576      0.533     0.489     0.373                3.6   
265        0.0     0.573      0.540     0.458     0.377                4.7   
318        5.4     0.591      0.561     0.474     0.352                4.5   
649        1.1     0.576      0.533     0.482     0.365                4.6   
785        1.8     0.574      0.542     0.488     0.380                4.3   
..         ...       ...        ...       ...       ...                ...   
106       -7.6     0.545      0.512     0.430     0.346                5.3   
270        5.3     0.578      0.540     0.445     0.350                5.7   
860        4.4     0.608      0.573     0.482     0.351                5.7   
435       -0.5     0.575      0.538     0.474     0.352                4.5   
102       -6.4     0.552      0.517     0.488     0.380                4.3   

     home_MOV  home_SRS  home_ORtg  home_NRtg  home_TS%  home_eFG%  
694      6.16      6.15      116.4        6.3     0.594      0.562  
265     -1.22     -1.18      111.2       -1.3     0.569      0.538  
318      3.13      2.87      109.9        3.1     0.570      0.538  
649     -4.73     -4.19      114.2       -4.8     0.581      0.551  
785      5.36      5.09      117.5        5.4     0.591      0.561  
..        ...       ...        ...        ...       ...        ...  
106     -8.25     -8.08      105.3       -8.4     0.528      0.492  
270     -6.55     -6.16      108.7       -6.4     0.552      0.517  
860      0.42      0.33      114.5        0.4     0.576      0.543  
435      3.13      2.87      109.9        3.1     0.570      0.538  
102      5.36      5.09      117.5        5.4     0.591      0.561  

[808 rows x 18 columns]

In [98]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_train

array([[-2.41276165e-01,  2.39004254e-01,  3.69947955e-01, ...,
         1.30543128e+00,  1.23868536e+00,  1.28513198e+00],
       [ 3.26358992e-01, -2.57862223e-01,  7.00244029e-01, ...,
        -3.16597857e-01, -1.64727297e-01, -3.97750536e-04],
       [ 1.39855873e+00,  7.91078118e-01, -9.51236343e-01, ...,
         6.22471641e-01, -1.08590791e-01, -3.97750536e-04],
       ...,
       [ 1.71391160e+00,  1.23273721e+00, -4.55792232e-01, ...,
         4.62244493e-02,  2.28228246e-01,  2.67420943e-01],
       [-1.78205592e-01, -8.65143473e-01, -1.28153242e+00, ...,
         6.22471641e-01, -1.08590791e-01, -3.97750536e-04],
       [-1.31347590e+00, -8.65143473e-01,  1.36083618e+00, ...,
         1.11334888e+00,  1.07027584e+00,  1.23156824e+00]])

In [99]:
scaled_X_test = scaler.transform(X_test)
scaled_X_test

array([[-0.99812304,  0.29421164,  1.36083618, ..., -1.59714717,
        -1.28745742, -1.12523626],
       [-0.24127616,  0.23900425,  0.36994795, ...,  1.28408879,
         1.51936789,  1.39225946],
       [ 0.01100613, -0.53389915,  0.70024403, ..., -1.59714717,
        -1.28745742, -1.12523626],
       ...,
       [ 1.7139116 ,  1.23273721, -0.45579223, ..., -0.89284505,
        -0.89450188, -1.07167253],
       [-0.55662903,  1.17752982,  1.19568814, ..., -0.03914551,
         0.05981873,  0.10672973],
       [ 0.26328842, -0.20265484, -1.77697653, ...,  1.28408879,
         1.51936789,  1.39225946]])

In [100]:
def preprocessing_function(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    scaled_X_train = scaler.fit_transform(X_train)
    scaled_X_test = scaler.transform(X_test)

    return scaled_X_train, scaled_X_test, y_train, y_test

In [101]:
from sklearn.svm import SVC

svc_clf = SVC()
svc_clf.fit(scaled_X_train, y_train)

SVC()

In [102]:
svc_clf_predictions = svc_clf.predict(scaled_X_test)
svc_clf_predictions

array(['Visitor', 'Home', 'Visitor', 'Home', 'Visitor', 'Visitor', 'Home',
       'Visitor', 'Visitor', 'Home', 'Home', 'Visitor', 'Visitor',
       'Visitor', 'Visitor', 'Visitor', 'Home', 'Home', 'Visitor',
       'Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor', 'Home', 'Home',
       'Home', 'Visitor', 'Home', 'Visitor', 'Home', 'Visitor', 'Visitor',
       'Home', 'Visitor', 'Visitor', 'Home', 'Home', 'Visitor', 'Home',
       'Visitor', 'Visitor', 'Visitor', 'Home', 'Home', 'Visitor',
       'Visitor', 'Home', 'Home', 'Visitor', 'Home', 'Visitor', 'Home',
       'Visitor', 'Visitor', 'Visitor', 'Visitor', 'Visitor', 'Visitor',
       'Visitor', 'Home', 'Visitor', 'Home', 'Home', 'Visitor', 'Visitor',
       'Home', 'Home', 'Visitor', 'Home', 'Home', 'Visitor', 'Visitor',
       'Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor', 'Home', 'Home',
       'Visitor', 'Home', 'Home', 'Visitor', 'Visitor', 'Visitor',
       'Visitor', 'Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor'

In [103]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

confusion_matrix(y_test, svc_clf_predictions)

array([[61, 50],
       [25, 67]])

In [104]:
accuracy_score(y_test, svc_clf_predictions)

0.6305418719211823

In [105]:
precision_score(y_test, svc_clf_predictions, pos_label="Home")

0.7093023255813954

In [106]:
recall_score(y_test, svc_clf_predictions, pos_label="Home")

0.5495495495495496

In [151]:
def algo_accuracy(y_test, predictions):
    conf_matrix = confusion_matrix(y_test, predictions)
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, pos_label="Home")
    recall = recall_score(y_test, predictions, pos_label="Home")

    return conf_matrix, accuracy, precision, recall

In [107]:
processing_data2 = game_schedule
processing_data2

Home/Away Winner
0                Home
1             Visitor
2                Home
3                Home
4                Home
...               ...
1006          Visitor
1007          Visitor
1008             Home
1009             Home
1010             Home

[1011 rows x 1 columns]

In [125]:
processing_data2["home_away_FG%_ratio"] = processing_data["home_FG%"]/processing_data["away_FG%"]
processing_data2["home_away_3P%_ratio"] = processing_data["home_3P%"]/processing_data["away_3P%"]
processing_data2["home_away_opponent_BLK_ratio"] = processing_data["home_opponent_BLK"]/processing_data["away_opponent_BLK"]
processing_data2["home_away_MOV_ratio"] = processing_data["home_MOV"]/processing_data["away_MOV"]
processing_data2["home_away_SRS_ratio"] = processing_data["home_SRS"]/processing_data["away_SRS"]
processing_data2["home_away_ORtg_ratio"] = processing_data["home_ORtg"]/processing_data["away_ORtg"]
processing_data2["home_away_NRtg_ratio"] = processing_data["home_NRtg"]/processing_data["away_NRtg"]
processing_data2["home_away_TS%_ratio"] = processing_data["home_TS%"]/processing_data["away_TS%"]
processing_data2["home_away_eFG%_ratio"] = processing_data["home_eFG%"]/processing_data["away_eFG%"]

processing_data2

Home/Away Winner  home_away_FG%_ratio  home_away_3P%_ratio  \
0                Home             1.060215             1.037433   
1             Visitor             0.983402             0.846154   
2                Home             0.991266             0.896552   
3                Home             1.030635             0.932817   
4                Home             0.928726             0.988571   
...               ...                  ...                  ...   
1006          Visitor             0.965665             1.042135   
1007          Visitor             0.989858             0.979381   
1008             Home             1.052036             1.093567   
1009             Home             0.969697             1.067416   
1010             Home             1.058957             1.167164   

      home_away_opponent_BLK_ratio  home_away_MOV_ratio  home_away_SRS_ratio  \
0                         1.022222           -15.785714           -25.312500   
1                         1.097561             0.519071             0.475166   
2                         1.170213             6.131148             6.296610   
3                         0.946429             0.008696            -0.020725   
4                         1.292683            18.750000            13.931034   
...                            ...                  ...                  ...   
1006                      1.075472             0.382979             0.059322   
1007                      0.934783             1.212670             1.256790   
1008                      0.865385             0.027833             0.016563   
1009                      0.941176            -0.962264            -0.369369   
1010                      0.735849            -1.225981            -1.204545   

      home_away_ORtg_ratio  home_away_TS%_ratio  home_away_eFG%_ratio  \
0                 1.074478             1.051903              1.049451   
1                 0.932146             0.951586              0.953901   
2                 0.953237             0.957821              0.951673   
3                 1.011733             1.026882              1.032505   
4                 0.958144             0.918261              0.914498   
...                    ...                  ...                   ...   
1006              1.007162             1.023256              1.013308   
1007              0.993238             0.972039              0.979058   
1008              1.063768             1.066421              1.068493   
1009              1.049416             1.028777              1.026923   
1010              1.105362             1.085610              1.088975   

      home_away_NRtg_ratio  
0               -14.666667  
1                 0.500000  
2                 5.846154  
3                 0.000000  
4                16.800000  
...                    ...  
1006              0.400000  
1007              1.227273  
1008              0.030303  
1009             -1.000000  
1010             -1.260274  

[1011 rows x 10 columns]

In [126]:
processing_data2 = processing_data2.replace([np.inf, -np.inf], np.nan).dropna(axis=1)
processing_data2

Home/Away Winner  home_away_FG%_ratio  home_away_3P%_ratio  \
0                Home             1.060215             1.037433   
1             Visitor             0.983402             0.846154   
2                Home             0.991266             0.896552   
3                Home             1.030635             0.932817   
4                Home             0.928726             0.988571   
...               ...                  ...                  ...   
1006          Visitor             0.965665             1.042135   
1007          Visitor             0.989858             0.979381   
1008             Home             1.052036             1.093567   
1009             Home             0.969697             1.067416   
1010             Home             1.058957             1.167164   

      home_away_opponent_BLK_ratio  home_away_MOV_ratio  home_away_SRS_ratio  \
0                         1.022222           -15.785714           -25.312500   
1                         1.097561             0.519071             0.475166   
2                         1.170213             6.131148             6.296610   
3                         0.946429             0.008696            -0.020725   
4                         1.292683            18.750000            13.931034   
...                            ...                  ...                  ...   
1006                      1.075472             0.382979             0.059322   
1007                      0.934783             1.212670             1.256790   
1008                      0.865385             0.027833             0.016563   
1009                      0.941176            -0.962264            -0.369369   
1010                      0.735849            -1.225981            -1.204545   

      home_away_ORtg_ratio  home_away_TS%_ratio  home_away_eFG%_ratio  
0                 1.074478             1.051903              1.049451  
1                 0.932146             0.951586              0.953901  
2                 0.953237             0.957821              0.951673  
3                 1.011733             1.026882              1.032505  
4                 0.958144             0.918261              0.914498  
...                    ...                  ...                   ...  
1006              1.007162             1.023256              1.013308  
1007              0.993238             0.972039              0.979058  
1008              1.063768             1.066421              1.068493  
1009              1.049416             1.028777              1.026923  
1010              1.105362             1.085610              1.088975  

[1011 rows x 9 columns]

In [127]:
y2 = processing_data2["Home/Away Winner"]
y2

0          Home
1       Visitor
2          Home
3          Home
4          Home
         ...   
1006    Visitor
1007    Visitor
1008       Home
1009       Home
1010       Home
Name: Home/Away Winner, Length: 1011, dtype: object

In [128]:
X2 = processing_data2.iloc[:,1:]
X2

home_away_FG%_ratio  home_away_3P%_ratio  home_away_opponent_BLK_ratio  \
0                1.060215             1.037433                      1.022222   
1                0.983402             0.846154                      1.097561   
2                0.991266             0.896552                      1.170213   
3                1.030635             0.932817                      0.946429   
4                0.928726             0.988571                      1.292683   
...                   ...                  ...                           ...   
1006             0.965665             1.042135                      1.075472   
1007             0.989858             0.979381                      0.934783   
1008             1.052036             1.093567                      0.865385   
1009             0.969697             1.067416                      0.941176   
1010             1.058957             1.167164                      0.735849   

      home_away_MOV_ratio  home_away_SRS_ratio  home_away_ORtg_ratio  \
0              -15.785714           -25.312500              1.074478   
1                0.519071             0.475166              0.932146   
2                6.131148             6.296610              0.953237   
3                0.008696            -0.020725              1.011733   
4               18.750000            13.931034              0.958144   
...                   ...                  ...                   ...   
1006             0.382979             0.059322              1.007162   
1007             1.212670             1.256790              0.993238   
1008             0.027833             0.016563              1.063768   
1009            -0.962264            -0.369369              1.049416   
1010            -1.225981            -1.204545              1.105362   

      home_away_TS%_ratio  home_away_eFG%_ratio  
0                1.051903              1.049451  
1                0.951586              0.953901  
2                0.957821              0.951673  
3                1.026882              1.032505  
4                0.918261              0.914498  
...                   ...                   ...  
1006             1.023256              1.013308  
1007             0.972039              0.979058  
1008             1.066421              1.068493  
1009             1.028777              1.026923  
1010             1.085610              1.088975  

[1011 rows x 8 columns]

In [129]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.2, random_state=10)
X2_train

home_away_FG%_ratio  home_away_3P%_ratio  home_away_opponent_BLK_ratio  \
193             1.014403             0.989796                      0.938776   
444             0.946721             0.973684                      1.186047   
384             1.027311             1.005391                      0.782609   
387             0.943205             0.963918                      0.978261   
953             0.987705             1.094737                      0.953488   
..                   ...                  ...                           ...   
320             0.899582             0.947945                      1.060000   
527             0.965164             0.950000                      1.232558   
996             1.065116             1.089595                      0.886792   
125             1.025581             0.968208                      1.000000   
265             0.972399             1.044321                      0.886792   

     home_away_MOV_ratio  home_away_SRS_ratio  home_away_ORtg_ratio  \
193             0.699367             0.655340              1.013710   
444             0.218284             0.249509              0.976170   
384             1.151402             1.116152              1.031915   
387            -0.063348            -0.039506              0.930685   
953             1.125000             1.186640              1.003404   
..                   ...                  ...                   ...   
320             5.124224             4.367568              0.949504   
527             0.003731            -0.007859              0.954043   
996             0.147879             0.146040              1.056030   
125             0.895758             0.925743              1.009497   
265           -61.000000            29.500000              0.991971   

     home_away_TS%_ratio  home_away_eFG%_ratio  
193             1.025295              1.014159  
444             0.974619              0.950089  
384             1.027682              1.040741  
387             0.950658              0.952880  
953             1.013536              1.005348  
..                   ...                   ...  
320             0.916667              0.897810  
527             0.969543              0.962567  
996             1.077652              1.093496  
125             1.039773              1.050813  
265             0.993019              0.996296  

[808 rows x 8 columns]

In [130]:
scaled_X2_train = scaler.fit_transform(X2_train)
scaled_X2_train

array([[ 0.25812826, -0.20367314, -0.384607  , ...,  0.22181022,
         0.51401976,  0.2306877 ],
       [-1.14107073, -0.42976444,  0.96382074, ..., -0.52743975,
        -0.61885487, -1.05930916],
       [ 0.52496953,  0.01516618, -1.23622188, ...,  0.58514755,
         0.5673719 ,  0.76588197],
       ...,
       [ 1.30652487,  1.19678603, -0.66808301, ...,  1.06645975,
         1.68446443,  1.82806176],
       [ 0.48921473, -0.50660934, -0.05073526, ...,  0.13771071,
         0.83767167,  0.96867828],
       [-0.61022919,  0.56146742, -0.66808301, ..., -0.21206867,
        -0.20751888, -0.12896813]])

In [132]:
scaled_X2_test = scaler.transform(X2_test)
scaled_X2_test

array([[-0.61022919,  0.56146742, -0.66808301, ..., -0.21206867,
        -0.20751888, -0.12896813],
       [-0.38275564, -0.56027797, -0.16928392, ..., -0.80333689,
        -0.47471137, -0.52943114],
       [-0.1699259 , -0.85478764,  0.18636207, ..., -0.47648155,
        -0.43823113, -0.42725149],
       ...,
       [-0.90461789,  0.40086815, -0.37792957, ...,  0.00216097,
        -0.32314008, -0.42180837],
       [ 2.02768088,  0.10174615, -0.56519172, ...,  0.91482725,
         1.64212479,  1.50067758],
       [-0.63271486, -1.09447286,  0.20290374, ..., -1.34277091,
        -0.84581252, -0.87986061]])

In [133]:
svc_clf2 = SVC()
svc_clf2.fit(scaled_X2_train, y2_train)

SVC()

In [135]:
svc_clf2_predictions = svc_clf2.predict(scaled_X2_test)
svc_clf2_predictions

array(['Home', 'Visitor', 'Visitor', 'Home', 'Home', 'Visitor', 'Home',
       'Home', 'Home', 'Home', 'Home', 'Home', 'Visitor', 'Visitor',
       'Home', 'Visitor', 'Home', 'Visitor', 'Visitor', 'Home', 'Home',
       'Home', 'Visitor', 'Home', 'Visitor', 'Visitor', 'Visitor', 'Home',
       'Home', 'Visitor', 'Visitor', 'Home', 'Home', 'Visitor', 'Home',
       'Visitor', 'Home', 'Visitor', 'Home', 'Visitor', 'Home', 'Visitor',
       'Home', 'Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor',
       'Visitor', 'Home', 'Home', 'Home', 'Home', 'Visitor', 'Visitor',
       'Visitor', 'Home', 'Visitor', 'Home', 'Visitor', 'Visitor',
       'Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor', 'Home', 'Home',
       'Visitor', 'Home', 'Home', 'Visitor', 'Home', 'Home', 'Visitor',
       'Visitor', 'Visitor', 'Home', 'Visitor', 'Visitor', 'Visitor',
       'Visitor', 'Visitor', 'Home', 'Home', 'Visitor', 'Home', 'Home',
       'Visitor', 'Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor',


In [136]:
confusion_matrix(y2_test, svc_clf2_predictions)

array([[69, 31],
       [34, 69]])

In [137]:
accuracy_score(y2_test, svc_clf2_predictions)

0.6798029556650246

In [139]:
precision_score(y2_test, svc_clf2_predictions, pos_label="Home")

0.6699029126213593

In [140]:
recall_score(y2_test, svc_clf2_predictions, pos_label="Home")

0.69

In [145]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = [
    {'n_estimators': [3, 10, 30], 'max_features': [2, 4, 6, 8]},
    {'bootstrap': [False], 'n_estimators': [3, 10], 'max_features': [2, 3, 4]},
]
rfc = RandomForestClassifier()

grid_search = GridSearchCV(rfc, param_grid, cv=5, scoring='accuracy', return_train_score=True)
grid_search.fit(scaled_X2_train, y2_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid=[{'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10, 30]},
                         {'bootstrap': [False], 'max_features': [2, 3, 4],
                          'n_estimators': [3, 10]}],
             return_train_score=True, scoring='accuracy')

In [147]:
rfc_clf = grid_search.best_estimator_
rfc_clf

RandomForestClassifier(max_features=2, n_estimators=30)

In [148]:
rfc_predictions = rfc_clf.predict(scaled_X2_test)
rfc_predictions

array(['Home', 'Visitor', 'Visitor', 'Home', 'Visitor', 'Home', 'Visitor',
       'Home', 'Home', 'Visitor', 'Visitor', 'Home', 'Visitor', 'Home',
       'Visitor', 'Home', 'Home', 'Home', 'Visitor', 'Home', 'Visitor',
       'Home', 'Visitor', 'Home', 'Visitor', 'Home', 'Visitor', 'Home',
       'Home', 'Visitor', 'Visitor', 'Home', 'Home', 'Home', 'Home',
       'Visitor', 'Home', 'Visitor', 'Home', 'Home', 'Home', 'Visitor',
       'Home', 'Visitor', 'Visitor', 'Visitor', 'Home', 'Home', 'Visitor',
       'Visitor', 'Visitor', 'Home', 'Home', 'Home', 'Home', 'Visitor',
       'Home', 'Home', 'Home', 'Home', 'Visitor', 'Home', 'Visitor',
       'Visitor', 'Visitor', 'Visitor', 'Home', 'Home', 'Visitor', 'Home',
       'Home', 'Home', 'Visitor', 'Visitor', 'Home', 'Home', 'Home',
       'Home', 'Visitor', 'Home', 'Visitor', 'Visitor', 'Home', 'Home',
       'Home', 'Visitor', 'Home', 'Home', 'Visitor', 'Visitor', 'Visitor',
       'Visitor', 'Visitor', 'Visitor', 'Visitor', 'Home', 'H

In [152]:
algo_accuracy(y2_test, rfc_predictions)

(array([[64, 36],
        [45, 58]]),
 0.6009852216748769,
 0.5871559633027523,
 0.64)

In [153]:
processing_data3 = game_schedule

processing_data3["home_away_FG%_plus_minus"] = processing_data["home_FG%"] - processing_data["away_FG%"]
processing_data3["home_away_3P%_plus_minus"] = processing_data["home_3P%"] - processing_data["away_3P%"]
processing_data3["home_away_opponent_BLK_plus_minus"] = processing_data["home_opponent_BLK"] - processing_data["away_opponent_BLK"]
processing_data3["home_away_MOV_plus_minus"] = processing_data["home_MOV"] - processing_data["away_MOV"]
processing_data3["home_away_SRS_plus_minus"] = processing_data["home_SRS"] - processing_data["away_SRS"]
processing_data3["home_away_ORtg_plus_minus"] = processing_data["home_ORtg"] - processing_data["away_ORtg"]
processing_data3["home_away_NRtg_plus_minus"] = processing_data["home_NRtg"] - processing_data["away_NRtg"]
processing_data3["home_away_TS%_plus_minus"] = processing_data["home_TS%"] - processing_data["away_TS%"]
processing_data3["home_away_eFG%_plus_minus"] = processing_data["home_eFG%"] - processing_data["away_eFG%"]

processing_data3

Home/Away Winner  home_away_FG%_ratio  home_away_3P%_ratio  \
0                Home             1.060215             1.037433   
1             Visitor             0.983402             0.846154   
2                Home             0.991266             0.896552   
3                Home             1.030635             0.932817   
4                Home             0.928726             0.988571   
...               ...                  ...                  ...   
1006          Visitor             0.965665             1.042135   
1007          Visitor             0.989858             0.979381   
1008             Home             1.052036             1.093567   
1009             Home             0.969697             1.067416   
1010             Home             1.058957             1.167164   

      home_away_opponent_BLK_ratio  home_away_MOV_ratio  home_away_SRS_ratio  \
0                         1.022222           -15.785714           -25.312500   
1                         1.097561             0.519071             0.475166   
2                         1.170213             6.131148             6.296610   
3                         0.946429             0.008696            -0.020725   
4                         1.292683            18.750000            13.931034   
...                            ...                  ...                  ...   
1006                      1.075472             0.382979             0.059322   
1007                      0.934783             1.212670             1.256790   
1008                      0.865385             0.027833             0.016563   
1009                      0.941176            -0.962264            -0.369369   
1010                      0.735849            -1.225981            -1.204545   

      home_away_ORtg_ratio  home_away_NRtg_ratio  home_away_TS%_ratio  \
0                 1.074478            -14.666667             1.051903   
1                 0.932146              0.500000             0.951586   
2                 0.953237              5.846154             0.957821   
3                 1.011733              0.000000             1.026882   
4                 0.958144             16.800000             0.918261   
...                    ...                   ...                  ...   
1006              1.007162              0.400000             1.023256   
1007              0.993238              1.227273             0.972039   
1008              1.063768              0.030303             1.066421   
1009              1.049416             -1.000000             1.028777   
1010              1.105362             -1.260274             1.085610   

      home_away_eFG%_ratio  home_away_FG%_plus_minus  \
0                 1.049451                     0.028   
1                 0.953901                    -0.008   
2                 0.951673                    -0.004   
3                 1.032505                     0.014   
4                 0.914498                    -0.033   
...                    ...                       ...   
1006              1.013308                    -0.016   
1007              0.979058                    -0.005   
1008              1.068493                     0.023   
1009              1.026923                    -0.014   
1010              1.088975                     0.026   

      home_away_3P%_plus_minus  home_away_opponent_BLK_plus_minus  \
0                        0.014                                0.1   
1                       -0.064                                0.4   
2                       -0.039                                0.8   
3                       -0.026                               -0.3   
4                       -0.004                                1.2   
...                        ...                                ...   
1006                     0.015                                0.4   
1007                    -0.008                               -0.3   
1008                     0.032                               -0.7   

In [156]:
processing_data3.drop(columns=["home_away_FG%_ratio", "home_away_3P%_ratio", "home_away_opponent_BLK_ratio", "home_away_MOV_ratio", "home_away_SRS_ratio", "home_away_ORtg_ratio", "home_away_NRtg_ratio", "home_away_TS%_ratio", "home_away_eFG%_ratio"], inplace=True)
processing_data3

Home/Away Winner  home_away_FG%_plus_minus  home_away_3P%_plus_minus  \
0                Home                     0.028                     0.014   
1             Visitor                    -0.008                    -0.064   
2                Home                    -0.004                    -0.039   
3                Home                     0.014                    -0.026   
4                Home                    -0.033                    -0.004   
...               ...                       ...                       ...   
1006          Visitor                    -0.016                     0.015   
1007          Visitor                    -0.005                    -0.008   
1008             Home                     0.023                     0.032   
1009             Home                    -0.014                     0.024   
1010             Home                     0.026                     0.056   

      home_away_opponent_BLK_plus_minus  home_away_MOV_plus_minus  \
0                                   0.1                      4.70   
1                                   0.4                     -2.90   
2                                   0.8                     -6.26   
3                                  -0.3                     -2.28   
4                                   1.2                     -7.81   
...                                 ...                       ...   
1006                                0.4                     -0.58   
1007                               -0.3                      0.94   
1008                               -0.7                      9.78   
1009                               -0.3                      1.04   
1010                               -1.4                     16.45   

      home_away_SRS_plus_minus  home_away_ORtg_plus_minus  \
0                         4.21                        8.2   
1                        -3.17                       -8.0   
2                        -6.25                       -5.2   
3                        -1.97                        1.3   
4                        -7.50                       -4.6   
...                        ...                        ...   
1006                     -1.11                        0.8   
1007                      1.04                       -0.8   
1008                      9.50                        6.6   
1009                      1.52                        5.5   
1010                     16.49                       11.2   

      home_away_NRtg_plus_minus  home_away_TS%_plus_minus  \
0                           4.7                     0.030   
1                          -3.1                    -0.029   
2                          -6.3                    -0.024   
3                          -2.4                     0.015   
4                          -7.9                    -0.047   
...                         ...                       ...   
1006                       -0.6                     0.013   
1007                        1.0                    -0.017   
1008                        9.6                     0.036   
1009                        1.0                     0.016   
1010                       16.5                     0.047   

      home_away_eFG%_plus_minus  
0                         0.027  
1                        -0.026  
2                        -0.026  
3                         0.017  
4                        -0.046  
...                         ...  
1006                      0.007  
1007                     -0.012  
1008                      0.035  
1009                      0.014  
1010                      0.046  

[1011 rows x 10 columns]

In [157]:
y3 = processing_data2["Home/Away Winner"]
y3

0          Home
1       Visitor
2          Home
3          Home
4          Home
         ...   
1006    Visitor
1007    Visitor
1008       Home
1009       Home
1010       Home
Name: Home/Away Winner, Length: 1011, dtype: object

In [159]:
X3 = processing_data3.iloc[:,1:]
X3

home_away_FG%_plus_minus  home_away_3P%_plus_minus  \
0                        0.028                     0.014   
1                       -0.008                    -0.064   
2                       -0.004                    -0.039   
3                        0.014                    -0.026   
4                       -0.033                    -0.004   
...                        ...                       ...   
1006                    -0.016                     0.015   
1007                    -0.005                    -0.008   
1008                     0.023                     0.032   
1009                    -0.014                     0.024   
1010                     0.026                     0.056   

      home_away_opponent_BLK_plus_minus  home_away_MOV_plus_minus  \
0                                   0.1                      4.70   
1                                   0.4                     -2.90   
2                                   0.8                     -6.26   
3                                  -0.3                     -2.28   
4                                   1.2                     -7.81   
...                                 ...                       ...   
1006                                0.4                     -0.58   
1007                               -0.3                      0.94   
1008                               -0.7                      9.78   
1009                               -0.3                      1.04   
1010                               -1.4                     16.45   

      home_away_SRS_plus_minus  home_away_ORtg_plus_minus  \
0                         4.21                        8.2   
1                        -3.17                       -8.0   
2                        -6.25                       -5.2   
3                        -1.97                        1.3   
4                        -7.50                       -4.6   
...                        ...                        ...   
1006                     -1.11                        0.8   
1007                      1.04                       -0.8   
1008                      9.50                        6.6   
1009                      1.52                        5.5   
1010                     16.49                       11.2   

      home_away_NRtg_plus_minus  home_away_TS%_plus_minus  \
0                           4.7                     0.030   
1                          -3.1                    -0.029   
2                          -6.3                    -0.024   
3                          -2.4                     0.015   
4                          -7.9                    -0.047   
...                         ...                       ...   
1006                       -0.6                     0.013   
1007                        1.0                    -0.017   
1008                        9.6                     0.036   
1009                        1.0                     0.016   
1010                       16.5                     0.047   

      home_away_eFG%_plus_minus  
0                         0.027  
1                        -0.026  
2                        -0.026  
3                         0.017  
4                        -0.046  
...                         ...  
1006                      0.007  
1007                     -0.012  
1008                      0.035  
1009                      0.014  
1010                      0.046  

[1011 rows x 9 columns]

In [160]:
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.2, random_state=10)
X3_train

home_away_FG%_plus_minus  home_away_3P%_plus_minus  \
193                     0.007                    -0.004   
444                    -0.026                    -0.010   
384                     0.013                     0.002   
387                    -0.028                    -0.014   
953                    -0.006                     0.036   
..                        ...                       ...   
320                    -0.048                    -0.019   
527                    -0.017                    -0.019   
996                     0.028                     0.031   
125                     0.011                    -0.011   
265                    -0.013                     0.016   

     home_away_opponent_BLK_plus_minus  home_away_MOV_plus_minus  \
193                               -0.3                     -1.90   
444                                0.8                     -4.19   
384                               -1.0                      0.81   
387                               -0.1                     -4.70   
953                               -0.2                      0.67   
..                                 ...                       ...   
320                                0.3                     -6.64   
527                                1.0                     -5.34   
996                               -0.6                      7.03   
125                                0.0                      0.86   
265                               -0.6                     -1.24   

     home_away_SRS_plus_minus  home_away_ORtg_plus_minus  \
193                     -2.13                        1.6   
444                     -3.82                       -2.8   
384                      0.64                        3.6   
387                     -4.21                       -8.2   
953                      0.95                        0.4   
..                        ...                        ...   
320                     -6.23                       -5.6   
527                     -5.13                       -5.4   
996                      6.90                        5.9   
125                      0.60                        1.0   
265                     -1.14                       -0.9   

     home_away_NRtg_plus_minus  home_away_TS%_plus_minus  \
193                       -1.7                     0.015   
444                       -4.3                    -0.015   
384                        1.0                     0.016   
387                       -4.7                    -0.030   
953                        0.8                     0.008   
..                         ...                       ...   
320                       -6.8                    -0.048   
527                       -5.4                    -0.018   
996                        7.1                     0.041   
125                        1.1                     0.021   
265                       -1.3                    -0.004   

     home_away_eFG%_plus_minus  
193                      0.008  
444                     -0.028  
384                      0.022  
387                     -0.027  
953                      0.003  
..                         ...  
320                     -0.056  
527                     -0.021  
996                      0.046  
125                      0.025  
265                     -0.002  

[808 rows x 9 columns]

In [161]:
scaled_X3_train = scaler.fit_transform(X3_train)
scaled_X3_train

array([[ 0.29683183, -0.17799534, -0.31312123, ..., -0.27775123,
         0.56113546,  0.27138258],
       [-1.17869462, -0.40676561,  0.97293306, ..., -0.66264554,
        -0.62030496, -1.08567028],
       [ 0.56510936,  0.05077492, -1.13151941, ...,  0.12194671,
         0.60051681,  0.79912536],
       ...,
       [ 1.23580321,  1.15649785, -0.66386331, ...,  1.02496799,
         1.58505049,  1.70382726],
       [ 0.47568352, -0.44489398,  0.03762085, ...,  0.13675034,
         0.79742354,  0.9122131 ],
       [-0.59742663,  0.5845722 , -0.66386331, ..., -0.21853672,
        -0.18711014, -0.10557655]])

In [162]:
scaled_X3_test = scaler.transform(X3_test)
scaled_X3_test

array([[-0.59742663,  0.5845722 , -0.66386331, ..., -0.21853672,
        -0.18711014, -0.10557655],
       [-0.37386201, -0.52115074, -0.07929318, ...,  1.14339701,
        -0.46277957, -0.52023159],
       [-0.1502974 , -0.82617775,  0.2714489 , ..., -1.16596888,
        -0.42339822, -0.40714385],
       ...,
       [-0.91041708,  0.43205869, -0.31312123, ...,  0.01832132,
        -0.30525418, -0.40714385],
       [ 1.90649705,  0.12703167, -0.54694928, ...,  0.86212809,
         1.54566914,  1.40225996],
       [-0.64213955, -1.09307639,  0.2714489 , ..., -0.36657299,
        -0.85659304, -0.89719072]])

In [163]:
svc_clf3 = SVC()
svc_clf3.fit(scaled_X3_train, y3_train)

SVC()

In [164]:
svc_clf3_predictions = svc_clf3.predict(scaled_X3_test)
svc_clf3_predictions

array(['Home', 'Home', 'Visitor', 'Home', 'Home', 'Visitor', 'Visitor',
       'Home', 'Home', 'Visitor', 'Home', 'Home', 'Visitor', 'Visitor',
       'Home', 'Visitor', 'Home', 'Visitor', 'Visitor', 'Home', 'Home',
       'Home', 'Visitor', 'Home', 'Visitor', 'Visitor', 'Home', 'Home',
       'Home', 'Visitor', 'Visitor', 'Home', 'Home', 'Visitor', 'Home',
       'Visitor', 'Home', 'Visitor', 'Home', 'Visitor', 'Home', 'Visitor',
       'Home', 'Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor',
       'Visitor', 'Home', 'Visitor', 'Home', 'Home', 'Visitor', 'Visitor',
       'Visitor', 'Home', 'Visitor', 'Home', 'Visitor', 'Visitor', 'Home',
       'Visitor', 'Visitor', 'Home', 'Visitor', 'Home', 'Home', 'Visitor',
       'Home', 'Home', 'Home', 'Visitor', 'Home', 'Visitor', 'Visitor',
       'Visitor', 'Home', 'Visitor', 'Visitor', 'Visitor', 'Visitor',
       'Visitor', 'Home', 'Visitor', 'Home', 'Home', 'Home', 'Visitor',
       'Visitor', 'Visitor', 'Visitor', 'Visitor', 'Visitor

In [165]:
confusion_matrix(y3_test, svc_clf3_predictions)

array([[67, 33],
       [28, 75]])

In [166]:
accuracy_score(y3_test, svc_clf3_predictions)

0.6995073891625616

In [167]:
precision_score(y3_test, svc_clf3_predictions, pos_label="Home")

0.7052631578947368

In [168]:
recall_score(y3_test, svc_clf3_predictions, pos_label="Home")

0.67

In [170]:
rfc = RandomForestClassifier()

grid_search2 = GridSearchCV(rfc, param_grid, cv=5, scoring='accuracy', return_train_score=True)
grid_search2.fit(scaled_X3_train, y3_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid=[{'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10, 30]},
                         {'bootstrap': [False], 'max_features': [2, 3, 4],
                          'n_estimators': [3, 10]}],
             return_train_score=True, scoring='accuracy')

In [171]:
rfc_clf2 = grid_search2.best_estimator_
rfc_clf2

RandomForestClassifier(max_features=8, n_estimators=3)

In [172]:
rfc_predictions2 = rfc_clf2.predict(scaled_X3_test)
rfc_predictions2

array(['Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor', 'Home', 'Home',
       'Home', 'Home', 'Visitor', 'Home', 'Home', 'Visitor', 'Visitor',
       'Home', 'Home', 'Home', 'Home', 'Visitor', 'Home', 'Home', 'Home',
       'Visitor', 'Home', 'Visitor', 'Visitor', 'Visitor', 'Home', 'Home',
       'Home', 'Visitor', 'Home', 'Home', 'Visitor', 'Home', 'Visitor',
       'Home', 'Home', 'Home', 'Home', 'Visitor', 'Visitor', 'Home',
       'Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor', 'Visitor',
       'Visitor', 'Visitor', 'Home', 'Home', 'Visitor', 'Home', 'Visitor',
       'Home', 'Visitor', 'Home', 'Visitor', 'Visitor', 'Home', 'Home',
       'Visitor', 'Visitor', 'Visitor', 'Visitor', 'Home', 'Visitor',
       'Home', 'Home', 'Home', 'Home', 'Home', 'Home', 'Home', 'Home',
       'Home', 'Visitor', 'Visitor', 'Home', 'Visitor', 'Home', 'Home',
       'Home', 'Visitor', 'Home', 'Home', 'Home', 'Visitor', 'Visitor',
       'Home', 'Home', 'Visitor', 'Visitor', 'Home', 'Home', 

In [173]:
algo_accuracy(y3_test, rfc_predictions2)

(array([[65, 35],
        [53, 50]]),
 0.5665024630541872,
 0.5508474576271186,
 0.65)

In [174]:
tuned_parameters = [
    {'kernel': ['rbf'], 'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
    {'kernel': ['linear'], 'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]}
]

grid_search3 = GridSearchCV(SVC(), tuned_parameters, scoring='accuracy', return_train_score=True)
grid_search3.fit(X3_train, y3_train)

GridSearchCV(estimator=SVC(),
             param_grid=[{'C': [0.1, 1, 10, 100, 1000],
                          'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [0.1, 1, 10, 100, 1000],
                          'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                          'kernel': ['linear']}],
             return_train_score=True, scoring='accuracy')

In [175]:
best_params3 = grid_search3.best_params_
best_estimator3 = grid_search3.best_estimator_

grid_search3_predictions = grid_search3.predict(X3_test)
algo_accuracy(y3_test, grid_search3_predictions)

(array([[69, 31],
        [31, 72]]),
 0.6945812807881774,
 0.69,
 0.69)

In [176]:
grid_search4 = GridSearchCV(SVC(), tuned_parameters, scoring='accuracy', return_train_score=True)
grid_search4.fit(scaled_X3_train, y3_train)

GridSearchCV(estimator=SVC(),
             param_grid=[{'C': [0.1, 1, 10, 100, 1000],
                          'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                          'kernel': ['rbf']},
                         {'C': [0.1, 1, 10, 100, 1000],
                          'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                          'kernel': ['linear']}],
             return_train_score=True, scoring='accuracy')

In [177]:
best_params4 = grid_search4.best_params_
best_estimator4 = grid_search4.best_estimator_

grid_search4_predictions = grid_search4.predict(scaled_X3_test)
algo_accuracy(y3_test, grid_search4_predictions)

(array([[67, 33],
        [28, 75]]),
 0.6995073891625616,
 0.7052631578947368,
 0.67)